// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAWlo_rEO2FYazfgGvweY1fEPLGDlwvsA',
    appId: '1:990336977881:web:3073fda9c99915f65027c8',
    messagingSenderId: '990336977881',
    projectId: 'ezshare-1a98f',
    authDomain: 'ezshare-1a98f.firebaseapp.com',
    storageBucket: 'ezshare-1a98f.appspot.com',
    measurementId: 'G-BH33GR17D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2mk7oJVnhriS4iXHVBYeC0inBqwukrJ8',
    appId: '1:990336977881:android:c9a353d7d50f631c5027c8',
    messagingSenderId: '990336977881',
    projectId: 'ezshare-1a98f',
    storageBucket: 'ezshare-1a98f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACMCxyS9kQkOS2GtnGTjBvyEoj3GOfuAU',
    appId: '1:990336977881:ios:0a518fa06d4415605027c8',
    messagingSenderId: '990336977881',
    projectId: 'ezshare-1a98f',
    storageBucket: 'ezshare-1a98f.appspot.com',
    androidClientId: '990336977881-9jnsae4ifeufb8qn9t4ucg2fiebu3jo7.apps.googleusercontent.com',
    iosClientId: '990336977881-3gkhdukdgtecfo0rhqd0qibd0tvt85n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACMCxyS9kQkOS2GtnGTjBvyEoj3GOfuAU',
    appId: '1:990336977881:ios:0a518fa06d4415605027c8',
    messagingSenderId: '990336977881',
    projectId: 'ezshare-1a98f',
    storageBucket: 'ezshare-1a98f.appspot.com',
    androidClientId: '990336977881-9jnsae4ifeufb8qn9t4ucg2fiebu3jo7.apps.googleusercontent.com',
    iosClientId: '990336977881-3gkhdukdgtecfo0rhqd0qibd0tvt85n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezshare',
  );
}
